import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
        {/* Navbar */}
        <nav className='px-2'>
          <div className='container flex item-center justify-between'>
            <h1 className='items-center text-4xl font-bold py-5 pl-16'>
              Lorem Ipsum
            </h1>
            <div className='w-3/4 items-center'>
              <ul className='flex justify-center p-4 mt-4'>
                <li>
                  <a className='block py-2 pl-3 pr-4' href="">Home</a>
                </li>
                <li>
                  <a className='block py-2 pl-3 pr-4 ' href="">Featured</a>
                </li>
                <li>
                  <a className='block py-2 pl-3 pr-4 ' href="">Service</a>
                </li>
                <li>
                  <a className='block py-2 pl-3 pr-4 ' href="">Contact Us</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>

        {/* Tittle */}
        <div className='pt-32'>
          <h1 className='text-2xl flex justify-center'>Life is Too Short For a Wide And Beautiful World</h1>

          <h1 className='text-6xl flex justify-center'>Enjoy Your Tour With Heavenly <br />Experience You've Never Had</h1>
        </div>

        {/* Card Pelayanan */}
        <div>

          <div className='bg-blue-700'>
            <img src="" alt="" />
            <p>Pelayanan</p>
          </div>


        </div>

      </main>
    </>
  )
}
